const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'src', 'i18n', 'translations.ts');
let content = fs.readFileSync(file, 'utf-8');

// The messed up part starts at `fr: {` and ends before `de: {`
const fixRegex = /fr: \{[\s\S]*?deployGuideTitle: 'دليل النشر والاستضافة على Cloudflare Pages'\n  \},/m;

const correctFrAndAr = `fr: {
    appName: 'DevPulse Utilitaires',
    appTagline: 'Suite 60-en-1 gratuite pour développeurs et créateurs',
    heroBadge: '100% côté client • Zéro journal serveur • Ultra rapide',
    heroTitle: 'Plus de 60 outils gratuits pour développeurs, designers,',
    heroTitleHighlight: 'enseignants et étudiants.',
    heroDescription: 'Des outils rapides et privés dans le navigateur pour le code, le design et l\\'apprentissage. Toutes les opérations s\\'exécutent localement.',
    searchPlaceholder: 'Rechercher 60+ utilitaires (ex: JSON, Base64, QR, Regex, SQL)...',
    searchAria: 'Rechercher des outils',
    searchShortcut: 'Appuyez sur ⌘K ou Ctrl+K pour rechercher',
    clientSideBadge: '100% Côté Client',
    freeForeverBadge: '100% Gratuit pour toujours',
    privacyBadge: 'Aucun Journal de Données',
    toolsCountBadge: '60 Utilitaires Essentiels',
    exploreAllTools: 'Explorer Tous Les Outils',
    viewDetails: 'Ouvrir L\\'outil',
    openTool: 'Lancer L\\'outil',
    favorite: 'Ajouter aux favoris',
    favorited: 'Ajouté aux favoris',
    copyUrl: 'Partager le lien',
    urlCopied: 'Lien copié dans le presse-papiers !',
    quickSearch: 'Recherche Rapide',
    noToolsFound: 'Aucun outil trouvé',
    noToolsFoundDesc: 'Essayez de modifier votre requête ou de changer de catégorie.',
    clearFilter: 'Réinitialiser les filtres',
    cat_all: 'Tous',
    cat_dev: 'Développeur & Code',
    cat_text: 'Texte & Rédaction',
    cat_media: 'Médias & Design',
    cat_security: 'Sécurité & Web',
    cat_converter: 'Maths & Convertisseurs',
    cat_education: 'Éducation & Étude',
    cat_everyday: 'Utilitaires Quotidiens',
    cat_design: 'Design & UI',
    cat_math: 'Maths & Finance',
    toolInstructions: 'Mode d\\'emploi',
    toolFaqs: 'Questions Fréquentes',
    toolRelated: 'Outils Similaires',
    backToTools: 'Retour aux outils',
    copyOutput: 'Copier le résultat',
    copied: 'Copié !',
    clear: 'Effacer',
    sample: 'Charger un exemple',
    download: 'Télécharger',
    reset: 'Réinitialiser',
    navHome: 'Accueil',
    navTools: 'Outils',
    navAbout: 'À Propos',
    navPrivacy: 'Confidentialité',
    navTerms: 'Conditions',
    navContact: 'Contact',
    navDeployGuide: 'Déploiement Cloudflare',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    language: 'Langue',
    allRightsReserved: 'Tous droits réservés.',
    footerTagline: 'Conçu pour les développeurs et les designers. 100% privé et prêt pour Cloudflare Pages.',
    hostedOnCloudflare: 'Optimisé pour Cloudflare Pages',
    privacyGuarantee: 'Garantie de Confidentialité : Vos données ne quittent jamais votre navigateur.',
    popularTools: 'Outils Populaires',
    aboutTitle: 'À Propos de DevPulse',
    privacyTitle: 'Politique de Confidentialité',
    termsTitle: 'Conditions d\\'Utilisation',
    contactTitle: 'Contact et Retours',
    deployGuideTitle: 'Guide de Déploiement Cloudflare Pages'
  },
  ar: {
    appName: 'أدوات ديف بلس',
    appTagline: '60 أداة مجانية للمطورين وصناع المحتوى في مكان واحد',
    heroBadge: '١٠٠٪ داخل المتصفح • بدون حفظ بيانات • فائق السرعة',
    heroTitle: 'أكثر من 60 أداة مجانية للمطورين، المصممين،',
    heroTitleHighlight: 'المعلمين والطلاب.',
    heroDescription: 'أدوات سريعة، آمنة، وتعمل بالكامل داخل متصفحك لإنجاز المهام اليومية، البرمجة، التصميم، والتعليم. جميع العمليات تتم محلياً على جهازك لضمان الخصوصية.',
    searchPlaceholder: 'ابحث بين أكثر من 60 أداة (مثال: JSON, Base64, QR, Regex, SQL)...',
    searchAria: 'البحث في الأدوات',
    searchShortcut: 'اضغط ⌘K أو Ctrl+K للبحث السريع',
    clientSideBadge: '١٠٠٪ محلي بالمتصفح',
    freeForeverBadge: 'مجاني بالكامل للأبد',
    privacyBadge: 'حماية كاملة للخصوصية',
    toolsCountBadge: '٦٠ أداة برمجية أساسية',
    exploreAllTools: 'استكشاف جميع الأدوات',
    viewDetails: 'فتح الأداة',
    openTool: 'تشغيل الأداة',
    favorite: 'إضافة للمفضلة',
    favorited: 'موجود في المفضلة',
    copyUrl: 'نسخ رابط الأداة',
    urlCopied: 'تم نسخ الرابط إلى الحافظة بنجاح!',
    quickSearch: 'بحث سريع',
    noToolsFound: 'لم يتم العثور على أي نتائج',
    noToolsFoundDesc: 'جرب تعديل كلمات البحث أو اختيار تصنيف آخر.',
    clearFilter: 'إعادة ضبط الفلاتر',
    cat_all: 'جميع الأدوات',
    cat_dev: 'التطوير والبرمجة',
    cat_text: 'النصوص والكتابة',
    cat_media: 'الوسائط والتصميم',
    cat_security: 'الأمان والويب',
    cat_converter: 'الرياضيات والتحويل',
    cat_education: 'التعليم والطلاب',
    cat_everyday: 'أدوات يومية',
    cat_design: 'التصميم والواجهات',
    cat_math: 'الرياضيات والمالية',
    toolInstructions: 'طريقة الاستخدام',
    toolFaqs: 'الأسئلة الشائعة',
    toolRelated: 'أدوات ذات صلة',
    backToTools: 'العودة لجميع الأدوات',
    copyOutput: 'نسخ النتيجة',
    copied: 'تم النسخ!',
    clear: 'مسح',
    sample: 'تحميل نموذج',
    download: 'تحميل الملف',
    reset: 'إعادة تعيين',
    navHome: 'الرئيسية',
    navTools: 'الأدوات',
    navAbout: 'من نحن',
    navPrivacy: 'سياسة الخصوصية',
    navTerms: 'الشروط والأحكام',
    navContact: 'اتصل بنا',
    navDeployGuide: 'نشر على Cloudflare',
    darkMode: 'الوضع الليلي',
    lightMode: 'الوضع النهاري',    
    language: 'اللغة',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    footerTagline: 'صُممت خصيصاً للمطورين والكتاب والمصممين. خصوصية كاملة ١٠٠٪ وجاهزة للنشر على Cloudflare Pages.',
    hostedOnCloudflare: 'مهيأ للنشر المباشر على Cloudflare Pages',
    privacyGuarantee: 'ضمان الخصوصية: بياناتك وملفاتك لا تغادر متصفحك أبداً.',
    popularTools: 'الأدوات الأكثر استخداماً',
    aboutTitle: 'عن منصة ديف بلس',
    privacyTitle: 'سياسة الخصوصية والأمان',
    termsTitle: 'شروط وأحكام الاستخدام',
    contactTitle: 'التواصل والاستفسارات',
    deployGuideTitle: 'دليل النشر والاستضافة على Cloudflare Pages'
  },`;

content = content.replace(fixRegex, correctFrAndAr);
fs.writeFileSync(file, content);
